### ISSUE TITLE
/var size increase

### ISSUE THREAD

**Issue by richard5netappcom** [NetAppDocs/bluexp-setup-admin#379] opened 2024-10-30 14:56 UTC
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-manual.html

### Page title

Manually install the Connector in Azure

### Summary

The /var size requirement needs to be bigger. My customers and my own testing shows a connector VM uses ~28GB in /var

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment] 2024-10-30 15:06
@richard5netappcom,

The product team is actively investigating the size requirement for /var

I passed your feedback on to them. I will update the documentation as soon as I get an update from the team.

Thanks,
Ben

**Comment by netapp-bcammett** [comment] 2024-11-01 14:21
I'm going to close this one as a duplicate of #377 which is where I'm tracking doc updates related to /var requirements.

Duplicate of #377

**Closed by netapp-bcammett** 2024-11-01 14:21 UTC
